/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.ClientController;
import domen.Clan;
import domen.Film;
import domen.Rezervacija;
import domen.Zaposleni;
import forme.clan.ClanForma;
import forme.clan.PretragaClanForma;
import forme.film.FilmForma;
import forme.film.PretragaFilmForma;
import forme.film.model.ModelTabeleFilm;
import forme.rezervacija.RezervacijaForma;
import forme.rezervacija.model.ModelTabeleRezervacija;
import forme.stavkarezervacije.model.ModelTabeleStavke;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author vanja
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    private ModelTabeleRezervacija mtr;
    private ModelTabeleStavke mts;

    public GlavnaForma() {
        try {
            initComponents();
            setLocationRelativeTo(null);
            Zaposleni z = ClientController.getInstanca().getUlogovani();
            jLabelIme.setText(z.getImeZaposlenog());
            jLabelPrezime.setText(z.getPrezimeZaposlenog());
            mts = new ModelTabeleStavke(new LinkedList<>());
            tblStavke.setModel(mts);
            popuniTabelu();
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelIme = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRezervacije = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnNovaRezervacija = new javax.swing.JButton();
        btnPretrazi = new javax.swing.JButton();
        btnIzmeniRezervaciju = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemNoviFilm = new javax.swing.JMenuItem();
        menuPretragaFilmova = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemNoviClan = new javax.swing.JMenuItem();
        menuItemPretragaClanovca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Dobrodosao, ");

        jLabelIme.setText("jLabel2");

        jLabelPrezime.setText("jLabel3");

        tblRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRezervacije.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRezervacijeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRezervacije);

        jLabel2.setText("Pretraga");

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavke);

        btnNovaRezervacija.setText("Nova rezervacija");
        btnNovaRezervacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaRezervacijaActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretrazi rezervaciju");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnIzmeniRezervaciju.setText("Izmeni rezervaciju");
        btnIzmeniRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniRezervacijuActionPerformed(evt);
            }
        });

        jMenu1.setText("Film");

        menuItemNoviFilm.setText("Novi film");
        menuItemNoviFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNoviFilmActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemNoviFilm);

        menuPretragaFilmova.setText("Pretraga filmova");
        menuPretragaFilmova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaFilmovaActionPerformed(evt);
            }
        });
        jMenu1.add(menuPretragaFilmova);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clan");

        menuItemNoviClan.setText("Novi clan");
        menuItemNoviClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNoviClanActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemNoviClan);

        menuItemPretragaClanovca.setText("Pretraga clanova");
        menuItemPretragaClanovca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaClanovcaActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemPretragaClanovca);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPrezime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeniRezervaciju)
                        .addGap(18, 18, 18)
                        .addComponent(btnNovaRezervacija))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(btnPretrazi)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelIme)
                    .addComponent(jLabelPrezime)
                    .addComponent(btnNovaRezervacija)
                    .addComponent(btnIzmeniRezervaciju))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemNoviFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNoviFilmActionPerformed
        FilmForma ff = new FilmForma(this, rootPaneCheckingEnabled, new Film());
        ff.setVisible(true);
    }//GEN-LAST:event_menuItemNoviFilmActionPerformed

    private void menuItemNoviClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNoviClanActionPerformed
        ClanForma cf = new ClanForma(this, rootPaneCheckingEnabled, new Clan());
        cf.setVisible(true);
    }//GEN-LAST:event_menuItemNoviClanActionPerformed

    private void menuItemPretragaClanovcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretragaClanovcaActionPerformed
        PretragaClanForma pcf = new PretragaClanForma(this, rootPaneCheckingEnabled);
        pcf.setVisible(true);
    }//GEN-LAST:event_menuItemPretragaClanovcaActionPerformed

    private void menuPretragaFilmovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaFilmovaActionPerformed
        PretragaFilmForma pff = new PretragaFilmForma(this, rootPaneCheckingEnabled);
        pff.setVisible(true);
    }//GEN-LAST:event_menuPretragaFilmovaActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        popuniTabelu();

    }//GEN-LAST:event_formWindowGainedFocus

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        popuniTabelu();
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void tblRezervacijeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRezervacijeMouseClicked
        try{
            int izabraniRed = tblRezervacije.getSelectedRow();
            if(izabraniRed> -1){
                Rezervacija r = mtr.vratiIzabranuRezervaciju(izabraniRed);
                Rezervacija ucitanaRezervacija = ClientController.getInstanca().ucitajStavkeRezervacije(r);
                mts.setList(ucitanaRezervacija.getStavke());
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tblRezervacijeMouseClicked

    private void btnIzmeniRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniRezervacijuActionPerformed
        try{
            int izabraniRed = tblRezervacije.getSelectedRow();
            if(izabraniRed> -1){
                Rezervacija r = mtr.vratiIzabranuRezervaciju(izabraniRed);
                Rezervacija ucitanaRezervacija = ClientController.getInstanca().ucitajStavkeRezervacije(r);
                new RezervacijaForma(this, rootPaneCheckingEnabled, ucitanaRezervacija).setVisible(true);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnIzmeniRezervacijuActionPerformed

    private void btnNovaRezervacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaRezervacijaActionPerformed
        new RezervacijaForma(this, rootPaneCheckingEnabled, new Rezervacija()).setVisible(true);
    }//GEN-LAST:event_btnNovaRezervacijaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniRezervaciju;
    private javax.swing.JButton btnNovaRezervacija;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem menuItemNoviClan;
    private javax.swing.JMenuItem menuItemNoviFilm;
    private javax.swing.JMenuItem menuItemPretragaClanovca;
    private javax.swing.JMenuItem menuPretragaFilmova;
    private javax.swing.JTable tblRezervacije;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {

        try {
            String pretraga = txtPretraga.getText();
            List<Rezervacija> lista;
            if (pretraga.isEmpty()) {
                lista = ClientController.getInstanca().ucitajListuRezervacija();
            } else {
                Rezervacija rez = new Rezervacija();
                Clan clan = new Clan();
                clan.setIme(pretraga);
                rez.setClan(clan);
                lista = ClientController.getInstanca().nadjiRezervacije(rez);
            }

            mtr = new ModelTabeleRezervacija(lista);
            tblRezervacije.setModel(mtr);
        } catch (Exception ex) {
            Logger.getLogger(PretragaFilmForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

