/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.film;

import controller.ClientController;
import domen.Film;
import domen.Reziser;
import domen.Zanr;
import forme.GlavnaForma;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vanja
 */
public class FilmForma extends javax.swing.JFrame {

    /**
     * Creates new form FilmForma
     */
    private Film film;
    private List<Reziser> reziseri;
    private List<Zanr> zanrovi;

    public FilmForma(java.awt.Frame parent, boolean modal, Film film) {
        initComponents();
        setLocationRelativeTo(null);
        napuniComboBoxZanrova();
        napuniComboBoxRezisera();
        this.film = film;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        if (film.getIdFilma() > 0) {
            jButtonSacuvaj.setText("Izmeni");
            jTextFieldNazivFilma.setText(film.getNaziv());
            jTextFieldGodina.setText(String.valueOf(film.getGodina()));
            jTextFieldBrojPrimeraka.setText(String.valueOf(film.getBrojPrimeraka()));
            jTextFieldPolica.setText(film.getPolica());
            jComboBoxZanr.setSelectedItem(film.getZanr().getNazivZanra());
            jComboBoxReziser.setSelectedItem(film.getReziser().getImeRezisera());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNazivFilma = new javax.swing.JTextField();
        jTextFieldBrojPrimeraka = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldGodina = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPolica = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxZanr = new javax.swing.JComboBox<>();
        jComboBoxReziser = new javax.swing.JComboBox<>();
        jButtonSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(" naziv");

        jLabel2.setText("broj primeraka");

        jLabel3.setText("godina");

        jLabel4.setText("polica");

        jLabel5.setText("Zanr");

        jLabel6.setText("Reziser");

        jComboBoxZanr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxReziser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxZanr, 0, 255, Short.MAX_VALUE)
                            .addComponent(jComboBoxReziser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPolica)
                            .addComponent(jTextFieldGodina)
                            .addComponent(jTextFieldNazivFilma)
                            .addComponent(jTextFieldBrojPrimeraka)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSacuvaj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNazivFilma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldBrojPrimeraka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPolica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxReziser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSacuvaj)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        try {
            String naziv = jTextFieldNazivFilma.getText();
            if (naziv.isEmpty()) {
                throw new Exception("Niste uneli naziv filma");
            }
            int brojPrimeraka = Integer.parseInt(jTextFieldBrojPrimeraka.getText());
            if (brojPrimeraka <= 0) {
                throw new Exception("Niste uneli validan broj primeraka");
            }
            String polica = jTextFieldPolica.getText();
            if (polica.isEmpty()) {
                throw new Exception("Niste uneli policu");
            }
            int godina = Integer.parseInt(jTextFieldGodina.getText());
            if (godina <= 0) {
                throw new Exception("Niste uneli validnu godinu");
            }
            Reziser reziser=null;
            for (Reziser r : reziseri) {
                if (r.toString().equals(jComboBoxReziser.getSelectedItem())) {
                    reziser = r;
                }
            }
            Zanr zanr=null;

            for (Zanr z : zanrovi) {
                if (z.toString().equals(jComboBoxZanr.getSelectedItem())) {
                    zanr = z;
                }

            }

            film.setBrojPrimeraka(brojPrimeraka);
            film.setGodina(godina);
            film.setPolica(polica);
            film.setNaziv(naziv);
            film.setZanr(zanr);
            film.setReziser(reziser);

            if (film.getIdFilma() > 0) {
                ClientController.getInstanca().izmeniFilm(film);
                JOptionPane.showMessageDialog(this, "Uspesno ste izmenili film");
            } else {
                ClientController.getInstanca().zapamtiFilm(film);
                JOptionPane.showMessageDialog(this, "Uspesno ste dodali film");

            }
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            ex.printStackTrace();
       }    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox<String> jComboBoxReziser;
    private javax.swing.JComboBox<String> jComboBoxZanr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldBrojPrimeraka;
    private javax.swing.JTextField jTextFieldGodina;
    private javax.swing.JTextField jTextFieldNazivFilma;
    private javax.swing.JTextField jTextFieldPolica;
    // End of variables declaration//GEN-END:variables

    private void napuniComboBoxRezisera() {
        try {
            reziseri = ClientController.getInstanca().ucitajListuRezisera();
            jComboBoxReziser.removeAllItems();
            for (Reziser r : reziseri) {
                jComboBoxReziser.addItem(r.toString());
            }
        } catch (Exception ex) {
            Logger.getLogger(FilmForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void napuniComboBoxZanrova() {
        try {
            zanrovi = ClientController.getInstanca().ucitajListuZanrova();
            jComboBoxZanr.removeAllItems();
            for (Zanr zanr : zanrovi) {
                jComboBoxZanr.addItem(zanr.toString());
            }
        } catch (Exception ex) {
            Logger.getLogger(FilmForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
